### ISSUE TITLE
Folders with git diffs don't get highlighted

### ISSUE THREAD

**Issue by brandonlilly** [trevordmiller/nova-atom-ui#19]
In this screenshot folder `foo` is selected, but there is no way to tell as the highlight is absent.
<img width="202" alt="screen shot 2016-09-25 at 9 19 07 pm" src="https://cloud.githubusercontent.com/assets/9450681/18822557/16181734-8366-11e6-8f1e-d7cc3fda25d7.png">

As far as I can tell this happens to any folder that has the git diff left border.

**Comment by trevordmiller** [comment]
@brandonlilly Thanks for letting me know

**Comment by callummr** [comment]
I think this is a fair fix for the issue, though I did mention an alternative in the PR - thoughts @trevordmiller?

**Comment by trevordmiller** [comment]
Thank you @callummr, your PR looks good. I'm on my phone right now and will be gone tonight but will review tomorrow and merge + publish. I appreciate your help :)
